### ISSUE TITLE
Zombies don't take fall damage

### ISSUE THREAD

**Issue by goerick** [zzm317/MyZombie#9]

**Comment by zzm317** [comment]
Because PM1.5 has changed a lot ...so some functions can never be used then

**Comment by goerick** [comment]
This has been fixed. Turns out to be a PocketMine bug with entities falling not getting damage

**Comment by goerick** [comment]
I don't know why you would discontinue the plugin....
Can you atleast make it private? What do you need in order to continue the plugin?

On Jun 21, 2015 6:16 AM, ZZM <notifications@github.com> wrote:Because PM1.5 has changed a lot ...so some functions can never be used then

**Comment by zzm317** [comment]
this plugin has never stop writing
because of one of the writter quit the team and some fuc*ing chinese people don't follow the plugin's license，I made this plugin private and ... I use another frame to widen this AI . Now the older frame can spawn almost all of the animals but because PM1.5 's foolish change ,the old frame get a lot of bugs.... So I rewrite a newer frame,now can support zombie,creeper and skeleton frquently...
If you want ti get the newest version of MyZombie.can you purchase for it? I know it's against the open-source license but I think if you paid for it, you won't reopen this plugin to public.. I hate the ones who go against the license.... (My English is not good enough so if there's some errors above.please don't mind for it)(Some people use myzombie's moving code into his plugin.and says that's his own plugin and it's different from myzombie and ...sell it.what the fuc*!)

**Comment by goerick** [comment]
And how much is it?

**Comment by zzm317** [comment]
I don't know what amount is suit for it....
Can you give me an example?
